# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 4 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: keshaB Paudel

description: this is where I rant
author:
  name: keshaB Paudel
  email: self@keshabpaudel.com.np
  github: poudel
  twitter: upasarga
 # pinterest: asd123
  #linkedin: asd123
  bio: I may be hostile.
  email_md5: f7b0b86a6708b75adb1fbf350e54f5de

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
