# Site settings
title: keshaB Paudel
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 my naive web diary
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://keshab.net" # the base hostname & protocol for your site
twitter_username: upasarga
github_username:  poudel

# Build settings
markdown: kramdown
